version: '3.8'
services:
  php-apache-environment:
    container_name: redlock20php
    build:
      context: ./php
      dockerfile: DockerFile
    depends_on:
      - Redlock
    volumes:
      - ./php/src:/var/www/html
    ports:
      - 7077:80

  Redlock:
    container_name: Redlock
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pw123
      MYSQL_DATABASE: Redlock
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"

  phmad:
    image: phpmyadmin/phpmyadmin
    ports:
      - '9000:80'
    restart: always
    environment:
      PMA_HOST: Redlock
    depends_on:
      - Redlock